name: Release
on:
  push:
    tags:
      - release/v**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install ruff
        run: pip install ruff
      - name: Lint with ruff
        run: ruff check .

  release-main:
    needs: lint
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and zip folder
        run: |
          tag_version="v1.0.17"
          version_tuple="1, 0, 17"
          # Copy the folder to a temp directory
          cp -r bms_blender_plugin bms_blender_plugin_tmp
          # Update only the version in the temp copy
          sed -i 's/"version": ([^)]*)/"version": ('$version_tuple')/' bms_blender_plugin_tmp/__init__.py
          # Zip the temp directory (will be named as required)
          zip -r "bms_blender_plugin-${tag_version}.zip" bms_blender_plugin_tmp
          # Remove the temp directory
          rm -rf bms_blender_plugin_tmp
          echo "Zip file built"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref }}"
          files: |
            bms_blender_plugin*.zip